controller_manager:
  ros__parameters:
    update_rate: 20
    use_sim_time: True

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


robot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheelfl_joint", "wheelbl_joint"]
    right_wheel_names: ["wheelfr_joint", "wheelbr_joint"]

    wheel_separation: 0.20
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.1]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.5] #[0.75, 0.75, 0.0, 0.0, 0.0, 0.5]

    position_feedback: True
    open_loop: False
    enable_odom_tf: True

    cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: True
    use_stamped_vel: False
    velocity_rolling_window_size: 10

    # preserve_turning_radius: True

    # publish_cmd: True

    # publish_wheel_data: True

    linear.x.has_velocity_limits: True
    linear.x.has_acceleration_limits: True
    linear.x.max_velocity: 0.26
    linear.x.min_velocity: -0.26
    linear.x.max_acceleration: 2.5
    linear.x.min_acceleration: -2.5

    angular.z.has_velocity_limits: True
    angular.z.has_acceleration_limits: True
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 4.0
    angular.z.min_acceleration: -4.0