name: Testing Merge Workflow.

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  testing-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Check for comment
        id: check_comment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TRIGGER_COMMENT="tos"
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT=$(gh pr view $PR_NUMBER --json comments --jq '.comments[].body')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "PR Comment: $COMMENT"
          COMMENT_LOWER=$(echo "$COMMENT" | tr '[:upper:]' '[:lower:]')
          if [[ "$COMMENT_LOWER" != *"$TRIGGER_COMMENT"* ]]; then
            echo "This PR will not be tested."
            echo "should_test=false" >> $GITHUB_OUTPUT 
            exit 1 
          else
            echo "This PR will be tested."
            echo "should_test=true" >> $GITHUB_OUTPUT
            exit 0
          fi
      
  revert_merge:
    runs-on: ubuntu-22.04
    needs: [testing-merge]
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 2

      - name: Configure Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
    
      - name: Revert the merge commit
        run: |
          # MERGE_COMMIT_SHA="${{ github.event.after }}"

          # git revert -m 1 "$MERGE_COMMIT_SHA"
          git revert -m 1 --no-edit ${{ github.sha }}

          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Inform PR
        run: |
          gh pr ${{ github.event.number }} --body "Workflow Falied and Changes Reverted"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

